#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# DO NOT share history between all sessions
unsetopt SHARE_HISTORY

# Force ls to output color, even when output is a pipe
export CLICOLOR_FORCE=1

tree() {
  command tree -C "$@" | less
}

alias watch='watch -c'
